// Generated by Wrangler on Sun Jul 21 2024 21:31:11 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
  ENVIRONMENT: string;
  VISITS: AnalyticsEngineDataset;
  RATE_LIMITER: any;
}
