name = "what-is-my-ip-dev"
main = "src/index.ts"
compatibility_date = "2024-07-06"
workers_dev = false
routes = [
    { pattern = "ip-dev.joaquingimenez.com", custom_domain = true }
]
analytics_engine_datasets = [
    { binding = "VISITS", dataset = "what_is_my_ip_dev" }
]

[vars]
ENVIRONMENT = "development"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[env.production]
name = "what-is-my-ip"
routes = [
    { pattern = "ip.joaquingimenez.com", custom_domain = true },
    { pattern = "ip.jg1.co", custom_domain = true }
]
analytics_engine_datasets = [
    { binding = "VISITS", dataset = "what_is_my_ip_prod" }
]

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 10, period = 60 }
