name = "what-is-my-ip-dev"
main = "src/index.ts"
compatibility_date = "2024-09-28"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
routes = [
  { pattern = "ip-dev.joaquingimenez.com", custom_domain = true }
]
analytics_engine_datasets = [
  { binding = "VISITS", dataset = "what_is_my_ip_dev" }
]
kv_namespaces = [
  { binding = "JWKS", id = "f0dc5d9ceb424bf6b6e1d538b4671879" }
]

[vars]
ENVIRONMENT = "development"
JWT_ISSUER = "https://joaquingimenez.cloudflareaccess.com"

[observability]
enabled = true
head_sampling_rate = 1

[version_metadata]
binding = "CF_VERSION_METADATA"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[env.production]
name = "what-is-my-ip"
routes = [
  { pattern = "ip.joaquingimenez.com", custom_domain = true },
  { pattern = "ip.jg1.co", custom_domain = true }
]
analytics_engine_datasets = [
  { binding = "VISITS", dataset = "what_is_my_ip_prod" }
]

[env.production.vars]
ENVIRONMENT = "production"

[env.production.observability]
enabled = true
head_sampling_rate = 1

[env.production.version_metadata]
binding = "CF_VERSION_METADATA"

[[env.production.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 10, period = 60 }
