name: Deploy

on:
  push:
    branches:
      - main
      - dev

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Install packages
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Deploy
        run: pnpm run deploy --env production

  dev-deploy:
    runs-on: ubuntu-latest
    name: Deploy to Development
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Install packages
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Deploy
        run: pnpm run deploy
