name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v3

      - name: Deploy to staging
        if: github.ref_name == 'staging'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            IPINFO_TOKEN
          command: deploy --env ${{ github.ref_name }}
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN_STAGING }}

      - name: Deploy to prod
        if: github.ref_name == 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            IPINFO_TOKEN
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN_PROD }}
