name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v3

      - name: Set production variable
        if: github.event.pull_request.base.ref == 'main' # check the target branch if it's master
        run: echo "WORKER_ENV=production" >> $GITHUB_ENV

      - name: Set production variable
        if: github.event.pull_request.base.ref == 'staging' # check the target branch if it's master
        run: echo "WORKER_ENV=production" >> $GITHUB_ENV

      - name: Deploy to GITHUB_ENV
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env $WORKER_ENV
