name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      WORKER_ENV: staging
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v3

      - name: Deploy to staging
        if: github.ref_name == 'staging'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env $WORKER_ENV

      - name: Deploy to prod
        if: github.ref_name == 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
