name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      WORKER_ENV: staging
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v3

      - name: Set WORKER_ENV to prod
        if: github.ref_name == 'main'
        run: echo "production" >> $WORKER_ENV

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env "${{ WORKER_ENV }}"
